site_name: Terraform Rockit Cloud Provider - User Guide
site_description: 'User documentation and reference for the
                   Terraform Rockit Cloud Provider'
use_directory_urls: false
copyright: Rockit Cloud
repo_name: C2Devel/terraform-provider-rockitcloud
repo_url: https://github.com/C2Devel/terraform-provider-rockitcloud
edit_uri: "https://github.com/C2Devel/terraform-provider-rockitcloud/tree/develop/website/docs"
nav:
  - Welcome: ./index.md             
  - Auto Scaling:
    - Resources:
      - aws_autoscaling_policy: r/autoscaling_policy.md
    - Data Sources:
      - aws_autoscaling_group: d/autoscaling_group.md
  - Backup:
    - Resources:
      - aws_backup_plan: r/backup_plan.md
      - aws_backup_selection: r/backup_selection.md
      - aws_backup_vault_default: r/backup_vault_default.md
    - Data Sources:
      - aws_backup_plan: d/backup_plan.md
      - aws_backup_selection: d/backup_selection.md
      - aws_backup_vault: d/backup_vault.md
  - CloudWatch:
    - Resources:
      - aws_cloudwatch_metric_alarm: r/cloudwatch_metric_alarm.md
  - Direct Connect:
    - Resources:
      - aws_dx_gateway: r/dx_gateway.md
      - aws_dx_gateway_association: r/dx_gateway_association.md
      - aws_dx_transit_virtual_interface: r/dx_transit_virtual_interface.md
    - Data Sources:
      - aws_dx_connection: d/dx_connection.md
      - aws_dx_gateway: d/dx_gateway.md
      - aws_dx_lag: d/dx_lag.md
  - EBS (EC2):
    - Resources:
      - aws_ebs_snapshot: r/ebs_snapshot.md
      - aws_ebs_snapshot_import: r/ebs_snapshot_import.md
      - aws_ebs_volume: r/ebs_volume.md
      - aws_snapshot_create_volume_permission: r/snapshot_create_volume_permission.md
      - aws_volume_attachment: r/volume_attachment.md
    - Data Sources:
      - aws_ebs_snapshot: d/ebs_snapshot.md
      - aws_ebs_snapshot_ids: d/ebs_snapshot_ids.md
      - aws_ebs_volume: d/ebs_volume.md
      - aws_ebs_volumes: d/ebs_volumes.md
  - EC2 (Elastic Compute Cloud):
    - Resources:
      - aws_ami: r/ami.md
      - aws_ami_from_instance: r/ami_from_instance.md
      - aws_ami_launch_permission: r/ami_launch_permission.md
      - aws_ec2_tag: r/ec2_tag.md
      - aws_eip: r/eip.md
      - aws_eip_association: r/eip_association.md
      - aws_instance: r/instance.md
      - aws_key_pair: r/key_pair.md
      - aws_launch_template: r/launch_template.md
      - aws_placement_group: r/placement_group.md
    - Data Sources:
      - aws_ami: d/ami.md
      - aws_ami_ids: d/ami_ids.md
      - aws_availability_zones: d/availability_zones.md
      - aws_availability_zone: d/availability_zone.md
      - aws_ec2_host: d/ec2_host.md
      - aws_eip: d/eip.md
      - aws_eips: d/eips.md
      - aws_instance: d/instance.md
      - aws_instances: d/instances.md
      - aws_key_pair: d/key_pair.md
      - aws_launch_template: d/launch_template.md
  - EKS (Elastic Kubernetes):
    - Resources:
      - aws_eks_cluster: r/eks_cluster.md
      - aws_eks_node_group: r/eks_node_group.md
    - Data Sources:
      - aws_eks_cluster: d/eks_cluster.md
      - aws_eks_cluster_auth: d/eks_cluster_auth.md
      - aws_eks_clusters: d/eks_clusters.md
      - aws_eks_node_group: d/eks_node_group.md
      - aws_eks_node_groups: d/eks_node_groups.md
  - ELB (Elastic Load Balancing):
    - Resources:
      - aws_lb: r/lb.md
      - aws_lb_listener: r/lb_listener.md
      - aws_lb_target_group: r/lb_target_group.md
      - aws_lb_target_group_attachment: r/lb_target_group_attachment.md
    - Data Sources:
      - aws_lb: d/lb.md
      - aws_lb_listener: d/lb_listener.md
      - aws_lb_target_group: d/lb_target_group.md
  - IAM (Identity & Access Management):
    - Resources:
      - aws_iam_group: r/iam_group.md
      - aws_iam_group_membership: r/iam_group_membership.md
      - aws_iam_group_policy_attachment: r/iam_group_policy_attachment.md
      - aws_iam_policy: r/iam_policy.md
      - aws_iam_project: r/iam_project.md
      - aws_iam_user: r/iam_user.md
      - aws_iam_user_group_membership: r/iam_user_group_membership.md
      - aws_iam_user_policy_attachment: r/iam_user_policy_attachment.md
    - Data Sources:
      - aws_iam_group: d/iam_group.md
      - aws_iam_policy: d/iam_policy.md
      - aws_iam_project: d/iam_project.md
      - aws_iam_user: d/iam_user.md
      - aws_iam_users: d/iam_users.md
  - PaaS:
    - Resources:
      - aws_paas_backup: r/paas_backup.md
      - aws_paas_service: r/paas_service.md
    - Data Sources:
      - aws_paas_backup: d/paas_backup.md
      - aws_paas_backup_users: d/paas_backup_users.md
      - aws_paas_backups: d/paas_backups.md
      - aws_paas_service: d/paas_service.md
  - Route 53:
    - Resources:
      - aws_route53_record: r/route53_record.md
      - aws_route53_zone: r/route53_zone.md
    - Data Sources:
      - aws_route53_zone: d/route53_zone.md
  - S3 (Simple Storage):
    - Resources:
      - aws_s3_bucket: r/s3_bucket.md
      - aws_s3_bucket_acl: r/s3_bucket_acl.md
      - aws_s3_bucket_cors_configuration: r/s3_bucket_cors_configuration.md
      - aws_s3_bucket_lifecycle_configuration: r/s3_bucket_lifecycle_configuration.md
      - aws_s3_bucket_object: r/s3_bucket_object.md
      - aws_s3_bucket_policy: r/s3_bucket_policy.md
      - aws_s3_bucket_request_payment_configuration: r/s3_bucket_request_payment_configuration.md
      - aws_s3_bucket_server_side_encryption_configuration: r/s3_bucket_server_side_encryption_configuration.md
      - aws_s3_bucket_versioning: r/s3_bucket_versioning.md
      - aws_s3_bucket_website_configuration: r/s3_bucket_website_configuration.md
      - aws_s3_object: r/s3_object.md
      - aws_s3_object_copy: r/s3_object_copy.md
    - Data Sources:
      - aws_canonical_user_id: d/canonical_user_id.md
      - aws_s3_bucket: d/s3_bucket.md
      - aws_s3_bucket_object: d/s3_bucket_object.md
      - aws_s3_bucket_objects: d/s3_bucket_objects.md
      - aws_s3_bucket_policy: d/s3_bucket_policy.md
      - aws_s3_object: d/s3_object.md
      - aws_s3_objects: d/s3_objects.md
  - Transit Gateway:
    - Resources:
      - aws_ec2_transit_gateway: r/ec2_transit_gateway.md
      - aws_ec2_transit_gateway_route: r/ec2_transit_gateway_route.md
      - aws_ec2_transit_gateway_route_table: r/ec2_transit_gateway_route_table.md
      - aws_ec2_transit_gateway_route_table_association: r/ec2_transit_gateway_route_table_association.md
      - aws_ec2_transit_gateway_route_table_propagation: r/ec2_transit_gateway_route_table_propagation.md
      - aws_ec2_transit_gateway_vpc_attachment: r/ec2_transit_gateway_vpc_attachment.md
    - Data Sources:
      - aws_ec2_transit_gateway: d/ec2_transit_gateway.md
      - aws_ec2_transit_gateway_dx_gateway_attachment: d/ec2_transit_gateway_dx_gateway_attachment.md
      - aws_ec2_transit_gateway_route_table: d/ec2_transit_gateway_route_table.md
      - aws_ec2_transit_gateway_route_tables: d/ec2_transit_gateway_route_tables.md
      - aws_ec2_transit_gateway_vpc_attachment: d/ec2_transit_gateway_vpc_attachment.md
      - aws_ec2_transit_gateway_vpc_attachments: d/ec2_transit_gateway_vpc_attachments.md
  - VPC (Virtual Private Cloud):
    - Resources:
      - aws_default_network_acl: r/default_network_acl.md
      - aws_default_route_table: r/default_route_table.md
      - aws_default_security_group: r/default_security_group.md
      - aws_default_vpc: r/default_vpc.md
      - aws_default_vpc_dhcp_options: r/default_vpc_dhcp_options.md
      - aws_main_route_table_association: r/main_route_table_association.md
      - aws_network_acl: r/network_acl.md
      - aws_network_acl_association: r/network_acl_association.md
      - aws_network_acl_rule: r/network_acl_rule.md
      - aws_network_interface: r/network_interface.md
      - aws_network_interface_attachment: r/network_interface_attachment.md
      - aws_network_interface_sg_attachment: r/network_interface_sg_attachment.md
      - aws_route: r/route.md
      - aws_route_table: r/route_table.md
      - aws_route_table_association: r/route_table_association.md
      - aws_security_group: r/security_group.md
      - aws_security_group_rule: r/security_group_rule.md
      - aws_subnet: r/subnet.md
      - aws_vpc: r/vpc.md
      - aws_vpc_dhcp_options: r/vpc_dhcp_options.md
      - aws_vpc_dhcp_options_association: r/vpc_dhcp_options_association.md
    - Data Sources:
      - aws_network_acls: d/network_acls.md
      - aws_network_interface: d/network_interface.md
      - aws_network_interfaces: d/network_interfaces.md
      - aws_route: d/route.md
      - aws_route_table: d/route_table.md
      - aws_route_tables: d/route_tables.md
      - aws_security_group: d/security_group.md
      - aws_security_groups: d/security_groups.md
      - aws_subnet: d/subnet.md
      - aws_subnet_ids: d/subnet_ids.md
      - aws_subnets: d/subnets.md
      - aws_vpc: d/vpc.md
      - aws_vpc_dhcp_options: d/vpc_dhcp_options.md
      - aws_vpcs: d/vpcs.md
  - VPN (Site-to-Site):
    - Resources:
      - aws_customer_gateway: r/customer_gateway.md
      - aws_vpn_gateway_route_propagation: r/vpn_gateway_route_propagation.md
    - Data Sources:
      - aws_customer_gateway: d/customer_gateway.md
      - aws_vpn_gateway: d/vpn_gateway.md
             
             
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    scheme: hashicorp
    primary: white
    accent: blue
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16

  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy

plugins:
  - search:
      lang:
        - en

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: "#"

extra_css:
     - 'assets/stylesheets/extra.css'
     - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
extra_javascript:
     - 'assets/stylesheets/extra.js'
