name: Run linters for the code

on:
  pull_request:
    branches: 'develop'
    paths: 'internal/**'
    types: 
      - labeled
      - opened
      - synchronize

jobs:
  code-linter:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: 1.21.x

    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install tools
      run: make tools

    - name: Install Docker
      uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # v4

    - name: Define owner
      if: contains(github.event.pull_request.labels.*.name, 'NeedSDK')
      env:
        PR_FORK_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
      run: |
        echo "FORK_OWNER=${PR_FORK_OWNER}" >> "$GITHUB_ENV"

    - name: Define aws-sdk-go's branch
      if: contains(github.event.pull_request.labels.*.name, 'NeedSDK')
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      run: |
        SDK_BRANCH=$(echo "${PR_BODY}" | grep -oE 'aws-sdk-go=[^[:space:]]+' || true)
        if [[ -n "$SDK_BRANCH" ]]; then
          BRANCH=$(echo "$SDK_BRANCH" | cut -d '=' -f2 | tr -d '\r')
        else
          BRANCH="${PR_HEAD_REF}"
        fi
        echo "AWS_SDK_GO_BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Define last commit of the fork
      if: contains(github.event.pull_request.labels.*.name, 'NeedSDK')
      run: |
        echo "FORK_COMMIT=$(git ls-remote https://github.com/${{ env.FORK_OWNER }}/aws-sdk-go.git ${{ env.AWS_SDK_GO_BRANCH }} |\
        cut -c1-7)">> $GITHUB_ENV

    - name: Bump version in go.mod
      if: contains(github.event.pull_request.labels.*.name, 'NeedSDK')
      run: |
        go mod edit -replace github.com/aws/aws-sdk-go=github.com/${{ env.FORK_OWNER }}/aws-sdk-go@${{ env.FORK_COMMIT }}

    - name: Apply dependencies
      run: go mod tidy

    - name: Run linters for the code
      run: make lint
