name: Run linters for the provider documentation

on:
  pull_request:
    branches: 'develop'
    paths: 'docs/**'

permissions:
  contents: read

jobs:
  docs-linter:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: 1.21.x

    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Install tools
      run: make tools

    - name: Install Docker
      uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # v4

    - name: Run linters for the docs
      run: make docs-lint
