name: Fixup checks

on:
  pull_request:
    branches: 'develop'
    types:
      - reopened
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  block-fixup:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        persist-credentials: false
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
